// ignore: constant_identifier_names
import '../pkg/save/model.dart';

const hostName = 'http://123.207.213.25';

List<WebSite> InitWebData = [
  WebSite(name:'google',webKey:'google',icon:'$hostName/icon/google.ico',url:''),
  WebSite(name:'腾讯',webKey:'tx',icon:'$hostName/icon/qq.ico',url:''),
  WebSite(name:'steam',webKey:'steam',icon:'$hostName/icon/steam.ico',url:''),
  WebSite(name:'github',webKey:'github',icon:'$hostName/icon/github.ico',url:''),
  WebSite(name:'bilibili',webKey:'bilibili',icon:'$hostName/icon/bilibili.ico',url:''),
  WebSite(name:'豆瓣',webKey:'douban',icon:'$hostName/icon/douban.ico',url:''),
  WebSite(name:'煎蛋',webKey:'jiandan',icon:'$hostName/icon/jiandan.ico',url:''),
  WebSite(name:'12306',webKey:'12306',icon:'$hostName/icon/12306.ico',url:''),
  WebSite(name:'三大妈',webKey:'3dm',icon:'$hostName/icon/3dm.ico',url:''),
  WebSite(name:'百度网盘',webKey:'baiduPan',icon:'$hostName/icon/baidu.ico',url:''),
  WebSite(name:'百度贴吧',webKey:'baidutieba',icon:'$hostName/icon/baidu.ico',url:''),
  WebSite(name:'学信网',webKey:'chsi',icon:'$hostName/icon/chsi.ico',url:''),
  WebSite(name:'当当网',webKey:'dangdang',icon:'$hostName/icon/dangdang.ico',url:''),
  WebSite(name:'斗鱼',webKey:'douyu',icon:'$hostName/icon/douyu.ico',url:''),
  WebSite(name:'facebook',webKey:'facebook',icon:'$hostName/icon/facebook.png',url:''),
  WebSite(name:'码云',webKey:'gitee',icon:'$hostName/icon/gitee.ico',url:''),
  WebSite(name:'instagram',webKey:'instagram',icon:'$hostName/icon/instagram.ico',url:''),
  WebSite(name:'京东',webKey:'jd',icon:'$hostName/icon/jd.ico',url:''),
  WebSite(name:'力扣',webKey:'leetcode',icon:'$hostName/icon/leetcode.ico',url:''),
  WebSite(name:'米哈游',webKey:'mihoyo',icon:'$hostName/icon/mihoyo.ico',url:""),
  WebSite(name:'原神',webKey:'ys',icon:'$hostName/icon/ys.ico',url:''),
  WebSite(name:'nc台服',webKey:'nctw',icon:'$hostName/icon/nctw.ico',url:''),
  WebSite(name:'牛客网',webKey:'nowcoder',icon:'$hostName/icon/nowcoder.ico',url:''),
  WebSite(name:'pinterest',webKey:'pinterest',icon:'$hostName/icon/pinterest.png',url:''),
  WebSite(name:'p站',webKey:'pixiv',icon:'$hostName/icon/pixiv.png',url:''),
  WebSite(name:'汤不热',webKey:'tumblr',icon:'$hostName/icon/tumblr.png',url:''),
  WebSite(name:'推特',webKey:'twitter',icon:'$hostName/icon/twitter.ico',url:''),
  WebSite(name:'微博',webKey:'weibo',icon:'$hostName/icon/weibo.ico',url:''),
  WebSite(name:'v2论坛',webKey:'v2ex',icon:'$hostName/icon/v2ex.png',url:''),
  WebSite(name:'小米',webKey:'xiaomi',icon:'$hostName/icon/mi.ico',url:''),
  WebSite(name:'宣城论坛',webKey:'xuancheng',icon:'$hostName/icon/xuancheng.ico',url:''),
  WebSite(name:'智联',webKey:'zhilian',icon:'$hostName/icon/zhilian.ico',url:''),
  WebSite(name:'知乎',webKey:'zhihu',icon:'$hostName/icon/zhihu.ico',url:''),
  WebSite(name:'a站',webKey:'acfun',icon:'$hostName/icon/acFun.ico',url:''),
  WebSite(name:'163',webKey:'163mail',icon:'$hostName/icon/163.ico',url:''),
  WebSite(name:'服务器',webKey:'server',icon:'$hostName/icon/server.ico',url:''),
  WebSite(name:'iccard',webKey:'iccard',icon:'$hostName/icon/iccard.ico',url:''),
  WebSite(name:'ohttps',webKey:'ohttps',icon:'$hostName/icon/ohttps.ico',url:''),
  WebSite(name:'七牛',webKey:'qiniu',icon:'$hostName/icon/qiniu.ico',url:''),
  WebSite(name:'cgray翻墙',webKey:'cgray',icon:'$hostName/icon/cgray.ico',url:''),
  WebSite(name:'hostingervps服务商',webKey:'hostinger',icon:'$hostName/icon/hostinger.ico',url:''),
  WebSite(name:'artstation',webKey:'artstation',icon:'$hostName/icon/artstation.ico',url:''),
  WebSite(name:'东方航空',webKey:'dfhk',icon:'$hostName/icon/dfhk.ico',url:''),
  WebSite(name:'交通部',webKey:'123123',icon:'$hostName/icon/123123.ico',url:''),
  WebSite(name:'ucloud',webKey:'ucloud',icon:'$hostName/icon/ucloud.ico',url:''),
  WebSite(name:'unsplash',webKey:'unsplash',icon:'$hostName/icon/unsplash',url:''),
  WebSite(name:'个税',webKey:'geshui',icon:'$hostName/icon/geshui.ico',url:'')
];
